package io.jevopt.jev;
import org.junit.jupiter.api.*;
import java.net.URI;import java.nio.charset.StandardCharsets;import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class JevClientTest {
 static final class Mock implements JevTransport { final List<Integer> statuses;final String body;int calls; Mock(List<Integer> statuses,String body){this.statuses=statuses;this.body=body;} public Response post(URI u,String auth,byte[] b,java.time.Duration t){calls++;return new Response(statuses.get(Math.min(calls-1,statuses.size()-1)),null,body.getBytes(StandardCharsets.UTF_8));} }
 JevQuestion choice(){return new JevQuestion("q1",JevQuestion.Type.CHOICE,"safe",List.of("a","b"));}
 String choiceResponse(){return "{\"model\":\"jev-1.13.0\",\"answers\":{\"q1\":{\"type\":\"choice\",\"choice\":\"a\",\"probabilities\":{\"a\":0.8,\"b\":0.2},\"confidence\":0.8}},\"usage\":{\"input_tokens\":1,\"output_tokens\":2}}";}
 @Test void choiceScoreAndNoulContracts() throws Exception {var m=new Mock(List.of(200),choiceResponse());var c=new JevClient(URI.create("http://127.0.0.1/x"),"token",false,true,m);assertEquals("a",c.ask("safe","jev-1.13.0",List.of(choice())).answers().getFirst().value());
  String score="{\"model\":\"jev-1.13.0\",\"answers\":{\"s\":{\"type\":\"score\",\"score\":0.3,\"legend\":{\"0\":\"low\",\"1\":\"high\"},\"probabilities\":{\"0\":0.7,\"1\":0.3},\"confidence\":0.7}},\"usage\":{\"input_tokens\":1,\"output_tokens\":2}}";assertEquals("0.3",new JevClient(URI.create("http://127.0.0.1/x"),"t",false,true,new Mock(List.of(200),score)).ask("safe","jev-1.13.0",List.of(new JevQuestion("s",JevQuestion.Type.SCORE,"safe",List.of("low","high")))).answers().getFirst().value());
  String noul="{\"model\":\"jev-1.13.0\",\"answers\":{\"n\":{\"type\":\"noul\",\"noul\":0.4}},\"usage\":{\"input_tokens\":1,\"output_tokens\":2}}";assertNull(new JevClient(URI.create("http://127.0.0.1/x"),"t",false,true,new Mock(List.of(200),noul)).ask("safe","jev-1.13.0",List.of(new JevQuestion("n",JevQuestion.Type.NOUL,"safe",List.of()))).answers().getFirst().confidence()); }
 @Test void offlineAndConsentFailBeforeTransport() {var m=new Mock(List.of(200),choiceResponse());assertThrows(IllegalStateException.class,()->new JevClient(URI.create("http://127.0.0.1/x"),"x",true,true,m).ask("safe","jev-1.13.0",List.of(choice())));assertThrows(IllegalStateException.class,()->new JevClient(URI.create("http://127.0.0.1/x"),"x",false,false,m).ask("safe","jev-1.13.0",List.of(choice())));assertEquals(0,m.calls);}
 @Test void retryRulesAndMalformedResponses() throws Exception {var retry=new Mock(List.of(429,529,200),choiceResponse());new JevClient(URI.create("http://127.0.0.1/x"),"x",false,true,retry).ask("safe","jev-1.13.0",List.of(choice()));assertEquals(3,retry.calls);for(int status:List.of(401,422)){var no=new Mock(List.of(status),choiceResponse());assertThrows(IllegalArgumentException.class,()->new JevClient(URI.create("http://127.0.0.1/x"),"x",false,true,no).ask("safe","jev-1.13.0",List.of(choice())));assertEquals(1,no.calls);}assertThrows(IllegalArgumentException.class,()->new JevClient(URI.create("http://127.0.0.1/x"),"x",false,true,new Mock(List.of(200),"{}")).ask("safe","jev-1.13.0",List.of(choice())));}
 @Test void endpointAndInputLimits() {assertThrows(IllegalArgumentException.class,()->new JevClient(URI.create("https://evil.example/x"),"x",false,true,(a,b,c,d)->null));assertThrows(IllegalArgumentException.class,()->new JevClient(URI.create("http://localhost/x"),"x",false,true,(a,b,c,d)->null));assertThrows(IllegalArgumentException.class,()->new JevClient(URI.create("http://127.0.0.1/x"),"x",false,true,(a,b,c,d)->null).ask("Bearer x","jev-1.13.0",List.of(choice())));assertThrows(IllegalArgumentException.class,()->new JevQuestion("q",JevQuestion.Type.CHOICE,"x",Collections.nCopies(256,"a")));}
}
