package io.jevopt.analyzers;
import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.Duration; import java.util.*; import java.util.concurrent.*;
/** Executes only a trusted configured executable using an argv array in an empty temporary directory. */
abstract class ProcessAnalyzer implements AnalyzerProvider {
 private final String id; private final Path executable; private final List<String> args; private final String credentialEnv;
 ProcessAnalyzer(String id,Path executable,List<String> args){this(id,executable,args,null);}
 ProcessAnalyzer(String id,Path executable,List<String> args,String credentialEnv){this.id=id;this.executable=executable.toAbsolutePath().normalize();this.args=List.copyOf(args);this.credentialEnv=credentialEnv;}
 public String id(){return id;} public AnalyzerCapabilities capabilities(){try{executable.toRealPath();return new AnalyzerCapabilities(Files.isRegularFile(executable,LinkOption.NOFOLLOW_LINKS)&&Files.isExecutable(executable)&&!Files.isSymbolicLink(executable),false,id.equals("claude"),"configured executable only; inference not invoked");}catch(IOException e){return new AnalyzerCapabilities(false,false,id.equals("claude"),"configured executable unavailable");}}
 protected AnalyzerResult parse(Path temp,String stdout) throws AnalyzerException {return StrictAnalyzerJson.parse(stdout,id);}
 public AnalyzerResult analyze(AnalyzerRequest request) throws AnalyzerException { if(!capabilities().available())throw new AnalyzerException("Configured executable unavailable"); Path temp=null;ExecutorService readers=Executors.newFixedThreadPool(2);try {temp=Files.createTempDirectory("jevopt-analyzer-");Files.writeString(temp.resolve("bundle.json"),request.bundle(),StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);Files.writeString(temp.resolve("schema.json"),StrictAnalyzerJson.SCHEMA,StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);List<String> command=new ArrayList<>();command.add(executable.toString());for(String arg:args)command.add(arg.replace("{temp}",temp.toString()));ProcessBuilder pb=new ProcessBuilder(command);pb.directory(temp.toFile());Map<String,String> env=pb.environment();env.clear();for(String n:List.of("PATH","LANG","LC_ALL"))if(System.getenv(n)!=null)env.put(n,System.getenv(n));if(credentialEnv!=null){String token=System.getenv(credentialEnv);if(token==null||token.isBlank())throw new AnalyzerException("Explicit configured credential unavailable");env.put(credentialEnv,token);}Process p=pb.start();Future<String> stdout=readers.submit(()->readCap(p.getInputStream()));Future<String> stderr=readers.submit(()->readCap(p.getErrorStream()));try(OutputStream in=p.getOutputStream()){in.write(("Analyze only the sanitized bundle. Return strict schema JSON.\\n"+request.bundle()).getBytes(StandardCharsets.UTF_8));} if(!p.waitFor(30,TimeUnit.SECONDS)){p.destroyForcibly();throw new AnalyzerException("Analyzer timed out");}String out=stdout.get(2,TimeUnit.SECONDS);stderr.get(2,TimeUnit.SECONDS);if(p.exitValue()!=0)throw new AnalyzerException("Analyzer failed");AnalyzerResult parsed=parse(temp,out);return new AnalyzerResult(parsed.provider(),parsed.version(),parsed.assessment(),parsed.confidence(),parsed.reasons(),new AnalyzerUsage(request.bundle().getBytes(StandardCharsets.UTF_8).length,out.getBytes(StandardCharsets.UTF_8).length,0,parsed.version()));}catch(AnalyzerException e){throw e;}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AnalyzerException("Analyzer execution interrupted");}catch(Exception e){throw new AnalyzerException("Analyzer execution failed");}finally{readers.shutdownNow();if(temp!=null)try(var paths=Files.walk(temp)){paths.sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(IOException ignored){}});}catch(IOException ignored){}}}
 private static String readCap(InputStream in)throws IOException{byte[] b=in.readNBytes(65_537);if(b.length>65_536)throw new IOException("Analyzer output limit exceeded");return new String(b,StandardCharsets.UTF_8);}
}
