package io.jevopt.analyzers;
import com.fasterxml.jackson.databind.*; import java.util.*;
final class StrictAnalyzerJson {
 static final String SCHEMA="{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"version\",\"assessment\",\"confidence\",\"reasons\"],\"properties\":{\"version\":{\"type\":\"string\"},\"assessment\":{\"enum\":[\"bounded\",\"unbounded\",\"unknown\"]},\"confidence\":{\"type\":\"number\"},\"reasons\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}}}}";
 static final ObjectMapper MAPPER=new ObjectMapper().enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS).enable(DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY);
 static AnalyzerResult parse(String raw,String provider) throws AnalyzerException { try { JsonNode n=MAPPER.readTree(raw); if(n==null||!n.isObject()||n.size()!=4||!Set.of("version","assessment","confidence","reasons").equals(fieldNames(n)))throw new AnalyzerException("Analyzer response schema rejected"); if(!n.get("version").isTextual()||n.get("version").asText().length()>80||!n.get("assessment").isTextual()||!n.get("confidence").isNumber()||!n.get("reasons").isArray()||n.get("reasons").size()>8)throw new AnalyzerException("Analyzer response schema rejected"); List<String> reasons=new ArrayList<>();for(JsonNode r:n.get("reasons")){if(!r.isTextual()||r.asText().length()>240)throw new AnalyzerException("Analyzer response schema rejected");reasons.add(r.asText());} return new AnalyzerResult(provider,n.get("version").asText(),n.get("assessment").asText(),n.get("confidence").asDouble(),reasons,null); }catch(AnalyzerException e){throw e;}catch(Exception e){throw new AnalyzerException("Analyzer response is not strict JSON");} }
 static AnalyzerResult parseClaude(String raw,String provider) throws AnalyzerException { try {JsonNode outer=MAPPER.readTree(raw);if(outer==null||!outer.isObject()||outer.get("structured_output")==null)throw new AnalyzerException("Analyzer response schema rejected");return parse(MAPPER.writeValueAsString(outer.get("structured_output")),provider);}catch(AnalyzerException e){throw e;}catch(Exception e){throw new AnalyzerException("Analyzer response is not strict JSON");} }
 private static Set<String> fieldNames(JsonNode n){Set<String>s=new HashSet<>();n.fieldNames().forEachRemaining(s::add);return s;}
}
